### ISSUE TITLE
Cross-Platform?

### ISSUE THREAD

**Issue by AustinBorger** [oscarlab/Be-Tree#1]
There's a number of unix-only functions called in this repo.  Is this intended to be just for linux, or for all platforms?

**Comment by rtjohnso** [comment]
Are there any outside of backingstore.{cpp,hpp}?

I would like everything else to be relatively portable, but I don't care if
backingstore is non-portable.

Best,
Rob

On Sun, Dec 13, 2015 at 12:12 AM, Austin Borger notifications@github.com
wrote:

> There's a number of unix-only functions called in this repo. Is this
> intended to be just for linux, or for all platforms?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/oscarlab/Be-Tree/issues/1.

## 

Calendar info:
https://www.google.com/calendar/embed?src=rob%40cs.stonybrook.edu

**Comment by AustinBorger** [comment]
test.cpp requires unistd, but that's the unit test.

**Comment by rtjohnso** [comment]
If you need to make test.cpp portable for you to work, go ahead.

And if you need to write a Windows or MacOS or FreeBSD version of
backingstore, go ahead.  (Or if you can make it portable via some simple
tweaks that don't make the code ugly).

But I consider those relatively low priority tasks unless those issues are
preventing you from getting work done.

Best,
Rob

On Sun, Dec 13, 2015 at 12:19 AM, Austin Borger notifications@github.com
wrote:

> test.cpp requires unistd, but that's the unit test.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/oscarlab/Be-Tree/issues/1#issuecomment-164228062.

## 

Calendar info:
https://www.google.com/calendar/embed?src=rob%40cs.stonybrook.edu
